// Wi-Fi
#define SECRET_USER_SETTINGS_SSID  "xxxxxx"
#define SECRET_USER_SETTINGS_PASSWORD "xxxxxxxxx" 

// MQTT
#define SECRET_USER_SETTINGS_MQTT_USER_ID "xxxxxx"
#define SECRET_USER_SETTINGS_MQTT_USER_PASS "xxxxxxxxxxxx"
